### ISSUE TITLE
Running npm install inside a terminal of VsCode on Arm64 Errors

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-react-sample#11]
Please delete this.

**Comment by ghost** [comment]
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/media/nvme/vscode-react-sample/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.4.154.c83-00028-gaeed0d91c4a7
gyp ERR! command "/home/linaro/.nvm/versions/node/v12.0.0/bin/node" "/media/nvme/vscode-react-sample/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /media/nvme/vscode-react-sample/node_modules/node-sass
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN material-ui@0.15.4 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN material-ui@0.15.4 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN material-ui@0.15.4 requires a peer of react-tap-event-plugin@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@1.2.1 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@1.2.1 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-todo@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:the copy
npm ERR!     /home/linaro/.npm/_logs/2019-04-29T15_29_20_035Z-debug.log

Ironically, I can build node-sass outside of VsCode and copy it to the local node-modules and that appears to work, but even after  copying, there is no persistence of data to the json or the view.
